CXX=clang++
IFLAGS=-I../../ -I../../include/ -I../ -I./ 
CFLAGS=$(IFLAGS) -g -std=c++11 -O3 -fPIC -pthread -Bsymbol

all: $(ALL)

%.o: %.cpp 
	$(CXX) $(CFLAGS) -c $^ -o $@

clean:
	rm -rf *.so *.o $(DEPS)
